export const paymentLinkData = [
  {
    id: 1,
    date: 'Nov 23',
    name: 'ahmed',
    type: 'buyer',
    amount: 300,
    status: 'closed',
    action: 'view',
  },
  {
    id: 1,
    date: 'Nov 23',
    name: 'ahmed',
    type: 'buyer',
    amount: 300,
    status: 'shipping',
    action: 'view',
  },
  {
    id: 1,
    date: 'Nov 23',
    name: 'ahmed',
    type: 'buyer',
    amount: 300,
    status: 'agreement',
    action: 'view',
  },
  {
    id: 1,
    date: 'Nov 23',
    name: 'ahmed',
    type: 'buyer',
    amount: 300,
    status: 'payment',
    action: 'view',
  },
  {
    id: 1,
    date: 'Nov 23',
    name: 'ahmed',
    type: 'buyer',
    amount: 300,
    status: 'delivery',
    action: 'view',
  },
];
